### ISSUE TITLE
Bitmap does not support HTMLVideoElement and HTMLCanvasElement

### ISSUE THREAD

**Issue by dyvoid** [mientjan/EaselTS#10]
The Bitmap class in the JS version supports passing an HTMLCanvasElement or HTMLVideoElement in the constructor. We should have that functionality as well. This will have consequences for the onLoad stuff.

**Comment by mientjan** [comment]
added BitmapVideo class

**Comment by mientjan** [comment]
will remove BitmapVideo, Bitmap now supports Video, canvas, image and string
