### ISSUE TITLE
setFps on stage not working

### ISSUE THREAD

**Issue by ThijsTyZ** [mientjan/EaselTS#23]
Cannot set the FPS on the

**Comment by dyvoid** [comment]
The ticker uses RAF timing by default, which means the browser is in charge of framerate (60fps usually). If you want to specify a particular fps, change the timingMode in the Ticker to anything other than TIMING_MODE_RAF.

**Comment by mientjan** [comment]
fixed, this now works through the Interval class. Now everytime you set the fps a new instance of the Interval class is spawned
