### ISSUE TITLE
Signal connect implementation

### ISSUE THREAD

**Issue by dyvoid** [mientjan/EaselTS#4]
See: https://github.com/mientjan/EaselTS/blob/master/src/createts/event/SignalAbstract.ts#L92

Why is it implemented in this weird way? The connect method can include the implementation directly (also works better for code completion). At the very least, connectImpl should be private.

**Comment by mientjan** [comment]
its just a second name for the same method. So the original version had connectImpl but i found that connect sounded better.

The implementation you are suggesting would require a second method call. This is more efficient.
