### ISSUE TITLE
Auto resizing

### ISSUE THREAD

**Issue by dyvoid** [mientjan/EaselTS#5]
See: https://github.com/dyvoid/EaselTS/blob/master/src/easelts/display/Stage.ts#L420-L427

Why is automatic resizing only enabled when passing a DIV element? Whether the canvas should size on window resize should not be forced anyway. Probably better to leave this decision to the developer and enabled/disable this functionality through a (constructor) variable?

In addition, it may be desirable to have this functionality not only for window resizing, but also for holder element resizing. We could potentially poll in onTick. May be a bit hacky.

**Comment by mientjan** [comment]
you have a point, originally this was because i not always knew the size of the canvas. I think we should implement it and see how good it is going to work.

**Comment by mientjan** [comment]
"In addition, it may be desirable to have this functionality not only for window resizing, but also for holder element resizing. We could potentially poll in onTick. May be a bit hacky."

There is no easy native way to detect a onresize on a domElement. And reading the size from the dom is too slow.
