### ISSUE TITLE
update TimeEvent param

### ISSUE THREAD

**Issue by dyvoid** [mientjan/EaselTS#6]
See: https://github.com/dyvoid/EaselTS/blob/master/src/easelts/display/Stage.ts#L492

Having TimeEvent as a required parameter prevents calling the update method manually. It cannot be assumed the Stage is only updated through a ticker.

**Comment by mientjan** [comment]
This is a legacy issue. the original code had something like this. The TimeEvent also needs to be removed and replaced with a delta:number.

**Comment by mientjan** [comment]
done
