### ISSUE TITLE
Rename BackgroundColor class?

### ISSUE THREAD

**Issue by dyvoid** [mientjan/EaselTS#7]
See: https://github.com/dyvoid/EaselTS/blob/master/src/easelts/component/BackgroundColor.ts

There is nothing about this class that exclusively makes it a background color. I understand that's what you use it for, but that's not what the class IS. Maybe rename it to ColoredBox or ColoredRectangle or the like?

**Comment by mientjan** [comment]
Yea that is a better naming convention. ill put it on my todo.

**Comment by mientjan** [comment]
renamed to SquarColor

**Comment by dyvoid** [comment]
There's a spelling mistake in there, it should be SquareColor. Also, I think this kind of goes against Easel naming convention. The method you use to draw is called drawRectangle, not drawSquare. I understand how ColoredRectangle sounds shitty, so here's a new proposal: how about calling it RectangleFill? Makes sense, since you do a beginFill and a drawRectangle. Describes pretty well what this is.

Additionaly I will add a CircleFill class. I often use rects and circles as quick, visual debug tools, so would be nice to have in the lib.

**Comment by mientjan** [comment]
"Additionaly I will add a CircleFill class. I often use rects and circles as quick, visual debug tools, so would be nice to have in the lib." 

Why not use the Debug class?

"RectangleFill"

is a not the right name because you can only fill with a color and with RectangleFill you also suggest a pattern fill

**Comment by dyvoid** [comment]
Forgot all about the Debug class, thanks, will use that in the future.

As for the 'fill' naming, I agree with what you're saying. Still don't see reason for using 'Square' over 'Rectangle' though.

**Comment by mientjan** [comment]
"Still don't see reason for using 'Square' over 'Rectangle' though." your right
